-- context_menu_api_demo.lua
-- Demo: multi-level context menu via the Context Menu API Lua callback.
--
-- Mirrors the MD demo mod (context_menu_api_demo.xml) but:
--   * registered via cmAPI.registerLuaCallback instead of MD signals
--   * all text labels have "[Lua]" prefix instead of "[MD]"
--   * action callbacks are plain Lua functions
--
-- MENU TREE:
--   [vanilla info_context / personnel]  (append)
--     ─── (separator)
--     [Lua] Test: Multi-Level Menu >   → cmt_lua_main
--     ─── (separator)
--     [Lua] Action 1   (menuItem, keepOpen, icon, textColor)
--     [Lua] Action 2   (menuItem)
--
--   [cmt_lua_main]   (custom mode — blank frame)
--     Name (Role)             (header — dynamic: resolved from data.person / data.entity)
--     < Back                  (auto-generated by API)
--     [Lua] Item A  >         → cmt_lua_sub_a
--     [Lua] Item B  >         → cmt_lua_sub_b
--
--   [cmt_lua_sub_a]
--     [Lua] Sub-Menu A  (header)
--     < Back
--     [Lua] A - Action 1
--     [Lua] A - Action 2
--
--   [cmt_lua_sub_b]
--     [Lua] Sub-Menu B  (header)
--     < Back
--     [Lua] B - Action 1
--     [Lua] B - Action 2

-- *** NPC label helper ***
-- FFI references — all declarations come from vanilla helper.lua / menu_map.lua.
local ffi = require("ffi")
local C   = ffi.C

-- Human-readable display names for raw GetPersonRole strings.
local roleDisplayNames = {
  pilot         = "Pilot",
  engineer      = "Engineer",
  service       = "Service Crew",
  marine        = "Marine",
  trainee_group = "Trainee",
  unassigned    = "Unassigned",
}

--- Return "<Name> (<Role>)" for the NPC referenced by *data*, or nil when
--- neither a person nor an entity is available.
local function getPersonLabel(data)
  if not data then return nil end
  if data.person and data.person ~= 0 then
    -- Crew NPC selected: resolve via NPCSeed + controllable component.
    local name    = ffi.string(C.GetPersonName(data.person, data.component))
    local roleStr = ffi.string(C.GetPersonRole(data.person, data.component))
    local role    = roleDisplayNames[roleStr] or roleStr
    return name .. " (" .. role .. ")"
  elseif data.entity then
    -- Instanced entity selected (pilot / captain / manager).
    local entity = ConvertStringTo64Bit(tostring(data.entity))
    local name   = ffi.string(C.GetComponentName(entity))
    local role
    if C.IsComponentClass(data.component, "ship_s") then
      role = "Pilot"
    elseif C.IsComponentClass(data.component, "ship") then
      role = "Captain"
    else
      role = "Manager"
    end
    return name .. " (" .. role .. ")"
  end
  return nil
end

-- *** Initialisation ***

local function Init()
  local cmAPI = require("extensions.context_menu_api.ui.context_menu_api")

  -- *** Entry builders per mode ***

  local function buildInfoContextEntries(menuName, rootMode, mode, data)
    return {
      { type = "separator" },
      {
        type = "subMenu",
        id   = "cmt_lua_main",
        text = "[Lua] Test: Multi-Level Menu",
      },
      { type = "separator" },
      {
        type      = "menuItem",
        id        = "cmt_lua_action_1",
        text      = "[Lua] Action 1",
        icon      = "order_follow",
        textColor = "text_positive",
        keepOpen  = true,
        onClick   = function(data, mode)
          DebugError("[CMAD-Lua] Action 1 triggered, mode=" .. tostring(mode))
        end,
      },
      {
        type    = "menuItem",
        id      = "cmt_lua_action_2",
        text    = "[Lua] Action 2",
        textColor = "text_negative",
        onClick = function(data, mode)
          DebugError("[CMAD-Lua] Action 2 triggered, mode=" .. tostring(mode))
        end,
      },
    }
  end

  local function buildMainMenuEntries(menuName, mode, rootMode, data)
    return {
      { type = "header", text = getPersonLabel(data) or "[Lua] Multi-Level Menu" },
      {
        type = "subMenu",
        id   = "cmt_lua_sub_a",
        text = "[Lua] Item A",
      },
      {
        type = "subMenu",
        id   = "cmt_lua_sub_b",
        text = "[Lua] Item B",
      },
    }
  end

  local function buildSubMenuAEntries(menuName, mode, rootMode, data)
    return {
      { type = "header", text = "[Lua] Sub-Menu A" },
      {
        type    = "menuItem",
        id      = "cmt_lua_a_action_1",
        text    = "[Lua] A - Action 1",
        onClick = function(data, mode)
          DebugError("[CMAD-Lua] A - Action 1 triggered")
        end,
      },
      {
        type    = "menuItem",
        id      = "cmt_lua_a_action_2",
        text    = "[Lua] A - Action 2",
        onClick = function(data, mode)
          DebugError("[CMAD-Lua] A - Action 2 triggered")
        end,
      },
    }
  end

  local function buildSubMenuBEntries(menuName, mode, rootMode, data)
    return {
      { type = "header", text = "[Lua] Sub-Menu B" },
      {
        type    = "menuItem",
        id      = "cmt_lua_b_action_1",
        text    = "[Lua] B - Action 1",
        onClick = function(data, mode)
          DebugError("[CMAD-Lua] B - Action 1 triggered")
        end,
      },
      {
        type    = "menuItem",
        id      = "cmt_lua_b_action_2",
        text    = "[Lua] B - Action 2",
        onClick = function(data, mode)
          DebugError("[CMAD-Lua] B - Action 2 triggered")
        end,
      },
    }
  end

  -- *** Dispatch table keyed by mode ***

  local modeBuilders = {
    info_context    = buildInfoContextEntries,
    personnel       = buildInfoContextEntries,
    cmt_lua_main    = buildMainMenuEntries,
    cmt_lua_sub_a   = buildSubMenuAEntries,
    cmt_lua_sub_b   = buildSubMenuBEntries,
  }

  -- *** Register as a Lua callback with the API ***

  cmAPI.registerLuaCallback(function(menuName, mode, rootMode, data)
    local builder = modeBuilders[mode]
    if not builder then return {} end
    return builder(menuName, mode, rootMode, data)
  end)
end

Register_OnLoad_Init(Init)
